# **SDG Prediction Validation**

## **Dependencies**

In [21]:
import pandas as pd
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## **Load Data**

### Load GIZ Project Data As Ground Truth

GIZ Running Projects can be used as ground truth for SDG.

In [2]:
running_giz_df = pd.read_excel("../../src/ground_truths/giz_running_projects.xlsx")

running_giz_df.head(1)

*Projektnummer                        Projektbezeichnung, deutsch  \
0    2008.9076.4  Unterstützung bei der Einführung eines Kühlsch...   

    Projektbezeichnung, englisch  CRS-Schlüssel  \
0  Refrigerator recycling system        41010.0   

                 CRS-Bezeichnung  CRS-Gewichtung  2. CRS-Schlüssel  \
0  Umweltpolitik und -verwaltung             1.0               NaN   

  2. CRS-Bezeichnung  2. CRS-Gewichtung  3. CRS-Schlüssel 3. CRS-Bezeichnung  \
0                NaN                NaN               NaN                NaN   

   3. CRS-Gewichtung  4. CRS-Schlüssel 4. CRS-Bezeichnung  4. CRS-Gewichtung  \
0                NaN               NaN                NaN                NaN   

  SDG Hauptziele                              Projektziele, deutsch  \
0         13;15;  Unterstützung beim Aufbau eines beispielhaften...   

                              Projektziele, englisch  \
0  Supporting the introduction of an exemplary ta...   

                                     BMZ-Schwerpunkt  
0  Umweltpolitik, Schutz und nachhaltige Nutzung ...

### Load Merged DF

In [3]:
df = pd.read_csv("../../src/merged_orgas.csv")
df.head(1)

C:\Users\UserNA6153\AppData\Local\Temp\ipykernel_15396\34694008.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../../src/merged_orgas.csv")


iati_id iati_orga_id orga_abbreviation  \
0  DE-1-199535469         DE-1               bmz   

                                      orga_full_name project_number  \
0  Bundesministerium für wirtschaftliche Zusammen...              1   

                   title_en                   title_other  \
0  Studies and Experts Fund  Studien- und Fachkräftefonds   

                 title_main  \
0  Studies and Experts Fund   

                                        organization country_code  ...  \
0  Bundesministerium für wirtschaftliche Zusammen...       ['NA']  ...   

            planned_end            actual_end           last_update  \
0  2026-12-31T00:00:00Z  2024-01-31T00:00:00Z  2024-01-31T00:00:00Z   

  crs_5_code         crs_5_name crs_3_code           crs_3_name  \
0    43010;   Multisector aid;       430;   Other Multisector;    

                                                docs sgd_pred_code  \
0  ['https://www.giz.de/projektdaten/projects.act...          15.0   

                                        sgd_pred_str  
0  Goal 15. Protect, restore and promote sustaina...  

[1 rows x 29 columns]

### Extract Project Numbers out of IATI ID

In [4]:
bmz_df = df[df.iati_orga_id == "DE-1"]

bmz_df["pn"] = "NaN"

for index, row in bmz_df.iterrows():
    try:
        pn_raw = row['iati_id'].split("-")[2]
        pn = f"{pn_raw[:4]}.{pn_raw[4:8]}.{pn_raw[8:]}"
        bmz_df.loc[index, "pn"] = pn
    except:
        pass

bmz_df.head(2)

C:\Users\UserNA6153\AppData\Local\Temp\ipykernel_15396\514410831.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bmz_df["pn"] = "NaN"


iati_id iati_orga_id orga_abbreviation  \
0  DE-1-199535469         DE-1               bmz   
1  DE-1-199665852         DE-1               bmz   

                                      orga_full_name project_number  \
0  Bundesministerium für wirtschaftliche Zusammen...              1   
1  Bundesministerium für wirtschaftliche Zusammen...              1   

                     title_en                     title_other  \
0    Studies and Experts Fund    Studien- und Fachkräftefonds   
1  Windhoek Water Reclamation  Abwasserrückgewinnung Windhoek   

                   title_main  \
0    Studies and Experts Fund   
1  Windhoek Water Reclamation   

                                        organization country_code  ...  \
0  Bundesministerium für wirtschaftliche Zusammen...       ['NA']  ...   
1  Bundesministerium für wirtschaftliche Zusammen...       ['NA']  ...   

             actual_end           last_update crs_5_code  \
0  2024-01-31T00:00:00Z  2024-01-31T00:00:00Z    43010;    
1  2024-01-31T00:00:00Z  2024-01-31T00:00:00Z    14020;    

                                      crs_5_name crs_3_code  \
0                              Multisector aid;       430;    
1  Water supply and sanitation - large systems;       140;    

                    crs_3_name  \
0          Other Multisector;    
1  Water Supply & Sanitation;    

                                                docs sgd_pred_code  \
0  ['https://www.giz.de/projektdaten/projects.act...          15.0   
1  ['https://www.kfw-entwicklungsbank.de/Internat...          12.0   

                                        sgd_pred_str           pn  
0  Goal 15. Protect, restore and promote sustaina...  1995.3546.9  
1  Goal 12. Ensure sustainable consumption and pr...  1996.6585.2  

[2 rows x 30 columns]

### Extract running GIZ projects just with one sdg to achieve better compareability 

In [5]:
running_giz_df = running_giz_df[running_giz_df['SDG Hauptziele'].str.len() == 3]

print(f"{len(running_giz_df)} with 1 SDG")
running_giz_df.head(1)

521 with 1 SDG


*Projektnummer                        Projektbezeichnung, deutsch  \
1    2010.9226.1   GIZ Mgmt - Vertrag 1 - Unterstützung des BMU ...   

                        Projektbezeichnung, englisch  CRS-Schlüssel  \
1  GIZ Mgmt - Vertrag 1 - Unterstützung des BMU b...        99810.0   

                                     CRS-Bezeichnung  CRS-Gewichtung  \
1  Nicht spezifizierte Sektoren (fortgeführt als ...             1.0   

   2. CRS-Schlüssel 2. CRS-Bezeichnung  2. CRS-Gewichtung  3. CRS-Schlüssel  \
1               NaN                NaN                NaN               NaN   

  3. CRS-Bezeichnung  3. CRS-Gewichtung  4. CRS-Schlüssel 4. CRS-Bezeichnung  \
1                NaN                NaN               NaN                NaN   

   4. CRS-Gewichtung SDG Hauptziele Projektziele, deutsch  \
1                NaN            17;           EU Twinning   

  Projektziele, englisch       BMZ-Schwerpunkt  
1            EU Twinning  Gestaltungsspielraum

### Match all running giz projects with IATI BMZ data 

In [6]:
# rename project number column in running_giz_df
running_giz_df.rename(columns={'*Projektnummer': 'pn'}, inplace=True)
running_giz_df.head(1)

pn                        Projektbezeichnung, deutsch  \
1  2010.9226.1   GIZ Mgmt - Vertrag 1 - Unterstützung des BMU ...   

                        Projektbezeichnung, englisch  CRS-Schlüssel  \
1  GIZ Mgmt - Vertrag 1 - Unterstützung des BMU b...        99810.0   

                                     CRS-Bezeichnung  CRS-Gewichtung  \
1  Nicht spezifizierte Sektoren (fortgeführt als ...             1.0   

   2. CRS-Schlüssel 2. CRS-Bezeichnung  2. CRS-Gewichtung  3. CRS-Schlüssel  \
1               NaN                NaN                NaN               NaN   

  3. CRS-Bezeichnung  3. CRS-Gewichtung  4. CRS-Schlüssel 4. CRS-Bezeichnung  \
1                NaN                NaN               NaN                NaN   

   4. CRS-Gewichtung SDG Hauptziele Projektziele, deutsch  \
1                NaN            17;           EU Twinning   

  Projektziele, englisch       BMZ-Schwerpunkt  
1            EU Twinning  Gestaltungsspielraum

In [8]:
# match with project number
merged_df = pd.merge(running_giz_df, bmz_df[['pn', 'sgd_pred_code']], on='pn', how='left')
merged_df.dropna(subset=['sgd_pred_code'], inplace=True)
print(f"{len(merged_df)}")
merged_df.head(5)

420


pn                        Projektbezeichnung, deutsch  \
3  2014.0968.9  Globalvorhaben Ernährungssicherung und Resilie...   
4  2014.2267.4         Modernisierung kommunaler Dienstleistungen   
5  2014.2267.4         Modernisierung kommunaler Dienstleistungen   
6  2014.2267.4         Modernisierung kommunaler Dienstleistungen   
7  2014.2267.4         Modernisierung kommunaler Dienstleistungen   

                        Projektbezeichnung, englisch  CRS-Schlüssel  \
3  Global programme Food and Nutrition Security, ...        43072.0   
4             Modernization of Local Public Services        43030.0   
5             Modernization of Local Public Services        43030.0   
6             Modernization of Local Public Services        43030.0   
7             Modernization of Local Public Services        43030.0   

                                     CRS-Bezeichnung  CRS-Gewichtung  \
3  Programme zur Ernährungssicherung auf Haushalt...             0.7   
4                   Stadtentwicklung und -verwaltung             1.0   
5                   Stadtentwicklung und -verwaltung             1.0   
6                   Stadtentwicklung und -verwaltung             1.0   
7                   Stadtentwicklung und -verwaltung             1.0   

   2. CRS-Schlüssel                                 2. CRS-Bezeichnung  \
3           43071.0  Politiken/Verwaltungsführung zur Ernährungssic...   
4               NaN                                                NaN   
5               NaN                                                NaN   
6               NaN                                                NaN   
7               NaN                                                NaN   

   2. CRS-Gewichtung  3. CRS-Schlüssel 3. CRS-Bezeichnung  3. CRS-Gewichtung  \
3                0.3               NaN                NaN                NaN   
4                NaN               NaN                NaN                NaN   
5                NaN               NaN                NaN                NaN   
6                NaN               NaN                NaN                NaN   
7                NaN               NaN                NaN                NaN   

   4. CRS-Schlüssel 4. CRS-Bezeichnung  4. CRS-Gewichtung SDG Hauptziele  \
3               NaN                NaN                NaN            02;   
4               NaN                NaN                NaN            11;   
5               NaN                NaN                NaN            11;   
6               NaN                NaN                NaN            11;   
7               NaN                NaN                NaN            11;   

                               Projektziele, deutsch  \
3  Die Ernährungssituation und die Resilienz gege...   
4  In ländlichen Gemeinden werden kommunale Diens...   
5  In ländlichen Gemeinden werden kommunale Diens...   
6  In ländlichen Gemeinden werden kommunale Diens...   
7  In ländlichen Gemeinden werden kommunale Diens...   

                              Projektziele, englisch  \
3  The food situation and the resilience to hunge...   
4  Efficient and sustainable provision of local p...   
5  Efficient and sustainable provision of local p...   
6  Efficient and sustainable provision of local p...   
7  Efficient and sustainable provision of local p...   

                                     BMZ-Schwerpunkt  sgd_pred_code  
3            Sicherung der Ernährung, Landwirtschaft            8.0  
4  Demokratie, Zivilgesellschaft, und öffentliche...            3.0  
5  Demokratie, Zivilgesellschaft, und öffentliche...            3.0  
6  Demokratie, Zivilgesellschaft, und öffentliche...            3.0  
7  Demokratie, Zivilgesellschaft, und öffentliche...            3.0

In [11]:
# just use most important columns
analy_df = merged_df[["pn", "SDG Hauptziele", "sgd_pred_code"]]
analy_df.head(400)

pn SDG Hauptziele  sgd_pred_code
3    2014.0968.9            02;            8.0
4    2014.2267.4            11;            3.0
5    2014.2267.4            11;            3.0
6    2014.2267.4            11;            3.0
7    2014.2267.4            11;            3.0
..           ...            ...            ...
658  2023.2125.5            16;            3.0
659  2023.2127.1            04;           14.0
667  2023.2169.3            08;           14.0
668  2023.2169.3            08;           14.0
672  2023.2177.6            10;           14.0

[400 rows x 3 columns]

In [14]:
# change dtype that both cols can be compared
analy_df["SDG Hauptziele"] = analy_df["SDG Hauptziele"].str[:2].astype(float)

analy_df.head()

C:\Users\UserNA6153\AppData\Local\Temp\ipykernel_15396\193875488.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  analy_df["SDG Hauptziele"] = analy_df["SDG Hauptziele"].str[:2].astype(float)


pn  SDG Hauptziele  sgd_pred_code
3  2014.0968.9             2.0            8.0
4  2014.2267.4            11.0            3.0
5  2014.2267.4            11.0            3.0
6  2014.2267.4            11.0            3.0
7  2014.2267.4            11.0            3.0

## **Analysis**

### Compare ground truth with predicted

In [24]:
cm = confusion_matrix(analy_df['SDG Hauptziele'], analy_df['sgd_pred_code'])
print(cm)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  5  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 13  0  0  0  0  0  1  0]
 [ 0  0  0  0  2  0  0  0  0 29  3  0  6 36 15  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 18  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0]
 [ 0  1  3  6  2  0  0  0  1  1  3  0  0 82 29  0]
 [ 0  0  0  0  1  0  0  0  0  1  0  2  4  0  3  0]
 [ 0  0  0  0  0  0  0  0  1  0  0  0  0  8  2  0]
 [ 4  0 12  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  7  1  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  5  0  2  0  0  1  0  0  0  0]
 [ 6  2 41  2  5  0  1  0  3  0  9  2  0 15 20  0]]
